# Generated by Django 3.0.4 on 2020-05-15 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('parent_id', models.IntegerField(default=0)),
                ('note', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.IntegerField(default=0),
        ),
    ]
